/**
 * Writes demo/config.js from the current deployment so the demo page points at it.
 *
 *   npx hardhat run scripts/demo-config.ts --network bscTestnet
 */
import { readFileSync, writeFileSync } from "node:fs";
import { network } from "hardhat";

const { networkName } = await network.create();
const d = JSON.parse(readFileSync(`deployments/${networkName}.json`, "utf8"));
const safe = JSON.parse(readFileSync(`deployments/${networkName}.safe.json`, "utf8"));
let demoAddress = "";
try { demoAddress = JSON.parse(readFileSync(`.demo-wallet.${networkName}.json`, "utf8")).address; } catch {}

const cfg = {
  network: networkName,
  chainId: d.chainId,
  chainName: d.chainId === 56 ? "BNB Smart Chain" : "BNB Smart Chain Testnet",
  rpcUrl: d.chainId === 56 ? "https://bsc-dataseed.bnbchain.org" : "https://bsc-testnet-rpc.publicnode.com",
  explorer: d.chainId === 56 ? "https://bscscan.com" : "https://testnet.bscscan.com",
  token: d.HVXToken,
  vault: d.HVXVestingVault,
  safe: safe.safeAddress,
  demoWallet: demoAddress,
};
writeFileSync("demo/config.js", `// generated by scripts/demo-config.ts\nwindow.HVX_CONFIG = ${JSON.stringify(cfg, null, 2)};\n`);
console.log(cfg);
