// generated by scripts/demo-config.ts
window.HVX_CONFIG = {
  "network": "bscTestnet",
  "chainId": 97,
  "chainName": "BNB Smart Chain Testnet",
  "rpcUrl": "https://bsc-testnet-rpc.publicnode.com",
  "explorer": "https://testnet.bscscan.com",
  "token": "0xB92f8c1e40D83389c70Bb654F83a71B8f4979d69",
  "vault": "0x414e9FA80ED96BA5181B7ab1aCeBFcA342C0C20C",
  "safe": "0x2D2A15e9c774166B8E2638dCbf989848e73c0F68",
  "demoWallet": "0xcd1FA94c98A63474CFcDF7464b174D2C7852AE65"
};
