// generated by scripts/demo-config.ts
window.HVX_CONFIG = {
  "network": "bscTestnet",
  "chainId": 97,
  "chainName": "BNB Smart Chain Testnet",
  "rpcUrl": "https://bsc-testnet-rpc.publicnode.com",
  "explorer": "https://testnet.bscscan.com",
  "token": "0x73d2230A6060180864E360c1e641767019cAB027",
  "vault": "0xc0A0C9F25526554b0c777124ADAC00Cc5aE2022a",
  "safe": "0xcA05ac7C594E2D7D2a16b8aebe56763500760779",
  "demoWallet": "0x403ac79402fB55Af1090CF0EBe88bA1d9Cfe8fAe"
};
