// generated by scripts/demo-config.ts
window.HVX_CONFIG = {
  "network": "bsc",
  "chainId": 56,
  "chainName": "BNB Smart Chain",
  "rpcUrl": "https://bsc-dataseed.bnbchain.org",
  "explorer": "https://bscscan.com",
  "token": "0x252Ce29d2a58B70f98fe80a67773747770Bb0028",
  "vault": "0x04d4D102eed59b34A1A6527b48cCa690daEeC8a3",
  "safe": "0xc5748294eE8884E7ac0bf27E0978cBA4c81b6d75",
  "demoWallet": ""
};
